app_walkers/urls.py
from django.contrib import admin
from django.urls import path , include


from .views import      WalkerListView   \
                    ,   WalkerDetailView \
                    ,   WalkerCreateView \
                    ,   WalkerUpdateView \
                    ,   WalkerDeleteView

from .router import router

app_name = "walkers"

urlpatterns = [
    path("", WalkerListView.as_view(), name="all"),
    path("create/", WalkerCreateView.as_view(), name="create"),
    path("<int:pk>/detail/",WalkerDetailView.as_view(), name="detail"),
    path("<int:pk>/update/",WalkerUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/",WalkerDeleteView.as_view(), name="delete")
]


# ahora vamos a la urls.py del manager


urlpatterns += router.urls

manager/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexPage
from .views import Form

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",IndexPage.as_view(),name="index"),
    path("form",Form.as_view(),name="form"),
    path("walkers/",include("app_walkers.urls"))
]

app_walkers/models.py
from django.db import models
from django.db.models import Model

# Create your models here.

class Walker(Model):
    SERVICES = [
        ("P", "Paseo"),
        ("C", "Cuidado"),
        ("A", "Alojamiento"),
    ]
    name = models.CharField(max_length=100,null=False,blank=False)
    image = models.CharField(max_length=300,null=False,blank=False)
    resume = models.CharField(max_length=200,null=False,blank=False)
    service = models.CharField(max_length=1, choices=SERVICES,null=False,blank=False)

    class Meta:
        db_table = "walkers_db"

    def __str__(self):
        return f"El profesional: {self.name}, brinda el siguiente servicio: {self.service}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

#luego registrar la app en Admin.py

app_walkers/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list   import ListView
from django.views.generic.edit   import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Walker

# Create your views here.


class WalkerBaseView(View):
    template_name = 'walkers.html'
    model = Walker
    fields = '__all__'
    success_url = reverse_lazy('walkers:all')


class WalkerListView(WalkerBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS VINOS
    """

class WalkerDetailView(WalkerBaseView,DetailView):
    template_name = "walkers_detail.html"

class WalkerCreateView(WalkerBaseView,CreateView):
    template_name = "walkers_create.html"
    extra_context = {
        "tipo": "Crear profesional"
    }


class WalkerUpdateView(WalkerBaseView,UpdateView):
    template_name = "walkers_create.html"
    extra_context = {
        "tipo": "Actualizar profesional"
    }

class WalkerDeleteView(WalkerBaseView,DeleteView):
    template_name = "walkers_delete.html"
    extra_context = {
        "tipo": "Borrar profesional"
    }


#--> ahora voya a urls.py de la app

manager/views.py
from django.views.generic import TemplateView
from django.http import JsonResponse

class IndexPage(TemplateView):
    template_name = "index.html"

class Form(TemplateView):
    template_name = "form.html"

app_walkers/templates/walkers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <div>
        <h1>Nuestros Profesionales</h1>
        <h2><a href="{% url 'walkers:create' %}">Crear</a></h2>
        {% for walker in walker_list%}
        <div class="list">
           <fieldset>
            <legend> Nombre: {{walker.name}}</legend>
            <ul>
                <li><img src="{% static '.{{walker.image}}' %}" alt="logo"></li>
                <li>{{walker.image}}</li>
                <li>Resumen: {{walker.resume}}</li>
                <li>Servicio que ofrece: {{walker.service}}</li>
            </ul>
            <span style="margin: 5px 5px 5px 150px;">
            <a style="color:blue;font-size: large;" href="{% url 'walkers:update' walker.id %}">Editar</a>
            </span>
            <span style="margin: 5px 5px 5px 150px;">
             <a style="color:red;font-size: large;" href="{% url 'walkers:delete' walker.id %}">Eliminar</a>
            </span>
            
        </div>
           </fieldset>
        </div>

        {% endfor %}
    </div>
</main>
{% endblock %}

app_walkers/templates/walkers_create.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_div}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'walkers:all' %}">Volvamos al Inicio</a>
    </div>
</main>
{% endblock %}

app_walkers/templates/walkers_delete.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div>
        <h1>Estas seguro ue deseas borrar este profesional?</h1>
        <h2>{{Walker.name}}</h2>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <input type="submit" value="{{ tipo }}" />
        </form>

        <a href="{% url 'walkers:all' %}">Cancelar</a>
    </div>
</main>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static './media/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static './media/images/favicon.ico' %}" type="image/x-icon"> 
    <title>Paseos | Codo23 Comision 23506 - Grupo 22</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
</head>
<body>
    
    <header> <!-- Inicio Header-->
        <nav class="navbar container">
            <picture class="navbar__logo">
                <a href="/">
                    <img src="{% static './media/images/logo.png' %}" alt="logo">
                </a>
            </picture>
           <ul class="navbar__menu">
                <li class="navbar__item">
                    <a class="navbar__link" href="{% url 'index' %}">HOME</a>
                </li>
                <li class="navbar__item">
                    <a class="navbar__link" href="{% url 'walkers:all' %}">CRUD</a>
                </li>
                
           </ul>    
        </nav>      
    </header> <!-- Fin Header-->
    <div class="post_header_line"></div>    
    
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <section class="footer-links">
            <ul class="footer-links__list">
                <li><a class="footer-links__link" href="./nosotros">Nosotros</a></li>
                <li><a class="footer-links__link" href="./reservas">Contacto</a></li>
                <li><a class="footer-links__link" href="">Redes Sociales</a></li>
            </ul>
        </section>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/iconify-icon@1.0.8/dist/iconify-icon.min.js"></script>
    <script src="{% static './js/resume.js' %}" type="text/javascript"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}


{% block content %}

    <main class="main-container">
        <section class="service-collection container">
            <article class="service-collection__content">
                    <h2 class="service-collection__title">Bienvenido al administrador de HappyPaws</h2>
                    <p class="service-collection__text">Desde esta sección podrás dar de alta, baja o modificar a los profesionales que trabajan con nosotros.</p>
                    <a class="service-collection__link" href="#">COMENZAR</a>
            </article>
            <picture class="collection__cover">
                <img src="{% static './media/images/paseo_pg.jpeg' %}" alt="Imagen del servicio de paseos">
            </picture>
        </section>
        <table class="table-resume container">
            <tr>
            <td class="table-headers" colspan="2">Nuestros profesionales</td>
             </tr>
            <tbody id="data-output">
                <!--populated from JS-->
            </tbody>
        </table>
    </main>
    {% endblock %}